options {
  directory "/var/cache/bind";
  recursion no;
  allow-query { any; };
  listen-on port 53 { any; };
  listen-on-v6 { none; };
  dnssec-validation auto;
};

zone "keddeh.com" IN {
  type master;
  file "/etc/bind/zones/db.keddeh.com";
  allow-transfer { none; };
};
